server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  security:
    user:
      name: username
      password: 123
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

h2:
  console:
    enabled: true